#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


def parse_gpu_ids(raw: str) -> list[int]:
    ids: list[int] = []
    seen: set[int] = set()
    for part in raw.split(","):
        value = part.strip()
        if not value:
            continue
        if not value.isdigit():
            raise argparse.ArgumentTypeError(f"GPU id must be a non-negative integer: {value!r}")
        gpu_id = int(value)
        if gpu_id in seen:
            raise argparse.ArgumentTypeError(f"Duplicate GPU id: {gpu_id}")
        seen.add(gpu_id)
        ids.append(gpu_id)
    if not ids:
        raise argparse.ArgumentTypeError("At least one GPU id is required.")
    return ids


def generate_compose(gpu_ids: list[int]) -> str:
    lines: list[str] = [
        "# Generated by tools/generate_gpu_compose.py.",
        "# Regenerate this file when the server GPU set changes.",
        "# NVIDIA_VISIBLE_DEVICES/device_ids select the host GPU.",
        "# CUDA_VISIBLE_DEVICES stays 0 because the selected GPU is remapped",
        "# to CUDA ordinal 0 inside each isolated container.",
        "services:",
    ]
    for gpu_id in gpu_ids:
        lines.extend(_worker_service(gpu_id))
        lines.extend(_rife_service(gpu_id))

    lines.append("volumes:")
    for gpu_id in gpu_ids:
        lines.append(f"  rife_gpu{gpu_id}_shared:")
    lines.append("")
    return "\n".join(lines)


def _worker_service(gpu_id: int) -> list[str]:
    return [
        f"  worker-gpu{gpu_id}:",
        "    build:",
        "      context: .",
        "      dockerfile: backend/worker/Dockerfile",
        "    env_file:",
        "      - .env",
        "    restart: unless-stopped",
        "    depends_on:",
        "      redis-db:",
        "        condition: service_healthy",
        "      pg-db:",
        "        condition: service_healthy",
        "      minio-db:",
        "        condition: service_healthy",
        f"      rife-gpu{gpu_id}:",
        "        condition: service_started",
        "    environment:",
        f"      RIFE_SERVICE_URL: http://rife-gpu{gpu_id}:3000",
        "      RIFE_SHARED_DIR: /shared/rife",
        "      RIFE_API_PATH: ${RIFE_API_PATH:-/interpolate_video}",
        "      RIFE_REQUEST_TIMEOUT: ${RIFE_REQUEST_TIMEOUT:-1800}",
        "    volumes:",
        f"      - rife_gpu{gpu_id}_shared:/shared/rife",
        '    command: ["python", "-m", "backend.worker.worker"]',
        "",
    ]


def _rife_service(gpu_id: int) -> list[str]:
    return [
        f"  rife-gpu{gpu_id}:",
        "    build:",
        "      context: ../video_interpolation_arch",
        "      dockerfile: services/practical_rife_bentoml/Dockerfile",
        "    restart: unless-stopped",
        "    environment:",
        '      CUDA_VISIBLE_DEVICES: "0"',
        f'      NVIDIA_VISIBLE_DEVICES: "{gpu_id}"',
        "      NVIDIA_DRIVER_CAPABILITIES: ${NVIDIA_DRIVER_CAPABILITIES:-compute,utility,video}",
        "      MODEL_WEIGHTS_ROOT: ${MODEL_WEIGHTS_ROOT:-/app/model_weights}",
        "      MODEL_REPOS_ROOT: ${MODEL_REPOS_ROOT:-/app/model_repos}",
        "      DATASET_ROOT: ${DATASET_ROOT:-/app/datasets}",
        "      RIFE_SHARED_DIR: /shared/rife",
        "      RIFE_DEVICE: ${RIFE_DEVICE:-cuda}",
        "      RIFE_CODEC: ${RIFE_CODEC:-h264_nvenc}",
        "      BENTOML_HOST: ${BENTOML_HOST:-0.0.0.0}",
        '      BENTOML_PORT: "${BENTOML_PORT:-3000}"',
        "    volumes:",
        f"      - rife_gpu{gpu_id}_shared:/shared/rife",
        "      - ../video_interpolation_arch/model_weights:/app/model_weights:ro",
        "      - ../video_interpolation_arch/model_repos:/app/model_repos:ro",
        "      - ../video_interpolation_arch/configs:/app/configs:ro",
        "    expose:",
        '      - "3000"',
        "    deploy:",
        "      resources:",
        "        reservations:",
        "          devices:",
        "            - driver: nvidia",
        f'              device_ids: ["{gpu_id}"]',
        "              capabilities: [gpu]",
        "",
    ]


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate GPU worker+BentoML Compose services for server deployment."
    )
    parser.add_argument(
        "--gpu-ids",
        required=True,
        type=parse_gpu_ids,
        help="Comma-separated GPU ids, for example: 0,1,2,3",
    )
    parser.add_argument(
        "--output",
        default="docker-compose.gpu.generated.yml",
        help="Output Compose file path.",
    )
    args = parser.parse_args()

    output_path = Path(args.output)
    output_path.write_text(generate_compose(args.gpu_ids), encoding="utf-8")
    print(f"Wrote {output_path} for GPU ids: {', '.join(str(gpu_id) for gpu_id in args.gpu_ids)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
